name: Autoupdate pre-commit

on:
  # To be able to be triggered manually
  workflow_dispatch:
  # To guarantee Maintained check is occasionally updated. See
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#maintained
  schedule:
    - cron: '28 2 * * 6' # Saturday at 02:28 UTC

permissions: read-all

jobs:
  autoupdate:
    name: Autoupdate

    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      # Needed to create a PR with autoupdate changes
      contents: write
      pull-requests: write

    steps:
      - name: Checkout DPNP repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.14'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate

      - name: Create a PR with autoupdate changes
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 #v8.1.0
        with:
          commit-message: 'chore: update pre-commit hooks'
          add-paths: .pre-commit-config.yaml
          branch: 'bot/pre-commit-autoupdate'
          delete-branch: true
          title: Weekly pre-commit autoupdate
          body: |
            This PR updates the `.pre-commit-config.yaml` using `pre-commit autoupdate`.
          labels: autoupdate
